# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "askr's blog"
email: mail@askr.cc
url: "https://blog.askr.dev"

description: >-
  欢迎访问我的个人博客, 这里专注于高性能计算(High-Performance Computing, HPC)领域的知识分享与技术解析。
  涵盖并行计算、GPU编程等主题。

twitter_username: 0xaskr
github_username:  0xaskr
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
# remote_theme: mmistakes/minimal-mistakes
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

show_drafts: false
future: true
lsi: false
strict_front_matter: true
baseurl: ""
source: ./
destination: ./_site
safe: true

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Asia/Shanghai"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name   : "askr"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "50%逻辑+30%好奇心+20%二次元<br/>
            是个码农"
  location : "Shanghai"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mail@askr.cc"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/0xaskr"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/0xaskr"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/0xaskr"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/0xaskr"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: false
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider               : "giscus"
  giscus:
    repo_id              : "R_kgDONe1rgw"
    category_name        : "Announcements"
    category_id          : "DIC_kwDONe1rg84Clkmg"
    discussion_term      : "pathname"
    reactions_enabled    : "1"
    theme                : "preferred_color_scheme"
    strict               : "0"
    input_position       : "top"
    emit_metadata        : "0"
    lang                 : "zh-CN"
    lazy                 : "true"

# Site Settings
locale                    : "zh-CN"
minimal_mistakes_skin     : "dirt"
repository                : "0xaskr/0xaskr.github.io"
enable_copy_code_button: true
